nastycode_task:
    resource: "@NastycodeTaskBundle/Resources/config/routing.php"
    prefix:   /

nasty_code_user:
    resource: "@NastycodeUserBundle/Resources/config/routing.yml"
    prefix:   /

nastycode_front:
    resource: "@NastycodeFrontBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@NastycodeUserBundle/Resources/config/routing/all.xml"

nastycode_post_code:
    path:     /post_code
    defaults: { _controller: NastycodeFrontBundle:Posts:posts }

nastycode_form_code:
    path:     /form
    defaults: { _controller: NastycodeTaskBundle:Default:index }
